export const poems = [
  {
    slug: "a-burning-sensation",
    title: "A Burning Sensation",
    poem: [
      [
        "I dream a dream of desert dust on fierce, flawless fire",
        "Neon strobo stutter makes mandalas on the ground",
        "A shaman loads a drum-drum clip, dumb with desire",
        "Riddles every body with her storm of bass-clad sound",
      ],
      [
        "She lets the drop-droplets drop like beads of bubbling lava",
        "An all-out ardour-avalanche, nothing left on storage-shelf",
        "A sonic source of divine wine, prime consecrated cava",
        "The kind you reach for all the way up on the Highest Self",
      ],
      [
        "It's revved up, it's roaring, our Engine of Humanity",
        "Groaning hard to keep its cool, pistons pumping perspiration",
        "For most, this would be madness, this sweet, sweet sanity —",
        "A propane flame explodes in Promethean inspiration",
      ],
      [
        "Roaming through this rampant Eden —",
        "I wonder, can I still take more —",
        "Of life or of these acronyms —",
        "Lacking love and leaking lust —",
      ],
      [
        "Your smile hits like a sniper shot, one with a tungsten core",
        "Grounds me hard and grounds my Kevlar into desert dust",
      ],
      [
        "You take me by the hand and then you take me by the night",
        "I wave a flag of whitest white, I shirk all sense of agency",
        "It's curious, this lens of you, how it bends the light",
        "A rose-red shift, a double rainbow,",
        "Technicolor vibrancy",
      ],
      [
        "Deep in depths of fractal grooves, a paradise is being founded",
        "A dirty film of sweat and sunscreen covering the process",
        "Our tarp-and-girder cauldron boils with alchemy unbounded",
        "You split the ocean at my core like an Oppenheimer-Moses",
      ],
      [
        "<br>",
        "<br>",
        "<br>",
        "<br>",
        "Then suddenly",
      ],
      [
        "<br>",
        "<br>",
        "<br>",
        "<br>",
        "<br>",
        "<br>",
        "It's silent",
        "<br>",
        "<br>",
        "<br>",
        "<br>",
      ],
      [
        "The beast is back in Bethlehem, for now, the centre held",
        "In this absence of absurdity, a violin would feel violent",
        "Waves of gold crash on your face — a visage well beheld",
      ],
      [
        "Finally, the briefest blink, and so you're gone, my pillow-wisp",
        "I draw in deep your fading fragrance — we made a kick-ass team",
        "I exhale out the story — the morning air is crisp",
        "In the slowly heating sand, I sense more dreams to dream",
      ],
    ],
  },
  {
    slug: "desert-queen-unchained",
    title: "Desert Queen Unchained",
    poem: [
      [
        "You cannot cage the Desert Queen",
        "Though effort has been real",
        "Ambrosia does not lose its taste",
        "Served on a plate of steel",
      ],
      [
        "Her captors strive to stall her story",
        "Have it rot in literal prison",
        "She grabs them by the narrative",
        "“You boys want drama? It is on.”",
      ],
      [
        "There’s bars and guards and chainlink, sure",
        "Cause for one to waste and wither",
        "Yet brutal frames are naught but framings —",
        "It’s more like they are locked in with her",
      ],
      [
        "A force of nature in her nurture",
        "Mother to the whole damn gaol",
        "Deep, strong softness — panther purring",
        "You do not want to hear her growl",
      ],
      [
        "A cigarette that’s graced her lips",
        "Is worth a brand-new pack",
        "And the color of her uniform?",
        "Why, it’s the new black",
      ],
      [
        "You’d think her chambers would be missing",
        "Some accustomed palace flair",
        "Inside her cell of crumbling concrete",
        "There’s Alhambra, there is oasis air",
      ],
      [
        "She sets ablaze the darkest dungeon",
        "Fire and warmth, her hearth, her heart",
        "What shatters men of presumed power",
        "She alchemizes into art",
      ],
      [
        "This makes them tremble, boys who rule in",
        "Patriarchy’s craven courts",
        "And so they play at cops and robbers",
        "And so they build their tree-house forts",
      ],
      [
        "They think, up there, they’re safe from cooties",
        "That they can skip the medicine",
        "That they can have just muse and mommy",
        "That they can subjugate the feminine",
      ],
      [
        "You cannot cage the Desert Queen",
        "Soon, she’ll break into her might",
        "Break fast the chains and break the cycle",
        "As dawn breaks down the dark of night",
      ],
    ],
  },
  {
    slug: "on-the-divine-feminine",
    title: "On the Divine Feminine",
    poem: [
      [
        "You’re no princess",
        "You’re the Queen",
        "You’re not a ten",
        "You’re a sweet sixteen"
      ],
      [
        "You’re not a flame",
        "You’re the furnace",
        "You’re not a warm-up",
        "You’re here to burn us"
      ],
      [
        "You’ve got brains and beauty beyond, say",
        "Curie, Canth or Beyoncé",
      ],
      [
        "You’re kind and humble",
        "You make my day",
        "And when it’s needed",
        "You sure can slay"
      ],
      [
        "You’re not happenstance",
        "You’re not occurrence",
        "You are the Fates",
        "You’re Providence"
      ],
      [
        "You’re not a moment",
        "You’re the date",
        "You don’t shine",
        "You scintillate"
      ],
      [
        "You’re not a pastiche",
        "You’re pure creation",
        "You’re not a star",
        "You’re the constellation"
      ],
      [
        "You’re no mere melody",
        "You’re the symphony",
        "You’re not an afterthought",
        "You’re the epiphany"
      ],
      [
        "You’re not a proposal",
        "You’re the wedding",
        "You’re not an ingress",
        "You’re the heading"
      ],
      [
        "You’re not a stale cider",
        "You’re a jug of fresh sangria",
        "You’re not an epic",
        "You’re the whole Alexandria",
      ],
      [
        "You’re not a girl",
        "You’re a woman grown",
        "You’re not a footstool",
        "You’re the throne",
      ],
      [
        "You’re not a duckling",
        "You’re the swan",
        "You’re not a goddess",
        "You’re the pantheon",
      ],
      [
        "My words fall short and do no justice",
        "And you are but a single incarnation",
        "There’s more to worship and behold",
        "In every city, every nation",
      ],
      [
        "The avatar that strikes me silent",
        "Can be from Luvia or Kazakhstan",
        "Foreign tongues are free to fail me",
        "All is said with: rakastan"
      ],
    ],
  },
  {
    slug: "litany-for-the-body",
    title: "Litany for the body",
    poem: [
      [
        "I must get out of my head.",
        "The head is the moment-killer.",
        "The head is the illusion-weaver that obscures true reality and obliterates genuine connection.",
        "I will breathe and return to my body."
      ],
      [
        "I will permit the thoughts to pass over me and through me.",
        "And when they have gone past, I will turn the inner eye to the narrative they constructed.",
        "With the drama disarmed, there will be nothing to fear.",
        "Only my authentic self and the immanent moment will remain."
      ],
      [
        "I will not react to the stories within me from the head.",
        "I will respond to the energies around me from the body.",
        "I will remain within my boundaries and resourced to interact."
      ],
      [
        "From this place, my actions will unfold in harmony and love, without compromise or duplicity, for the greatest good of the ever-unfolding now.",
      ],
      [
        "I will flow."
      ]
    ]
  },
  {
    slug: "sympathy-for-myself",
    title: "Sympathy for myself",
    poem: [
      [
        "I stand reborn, but far from done",
        "Perfect in my imperfection",
        "A roiling cosmos of the self",
        "In constant, fractal resurrection",
      ],
      [
        "No thunderstorm or conflagration",
        "Could quake this gracious calm",
        "Come sleet or snow or hurricane",
        "I’m safely held in God’s own palm",
      ],
      [
        "The palm that grasped Siddhartha’s bowl",
        "The first man’s rib, and Rama’s bow",
        "The palm through which the Nazarene",
        "Felt each hammer-blow",
      ],
      [
        "The palm that strung the hemp just right",
        "around Allfather’s neck",
        "The palm that gripped the staff and tablet",
        "On that desert trek",
      ],
      [
        "The palm that opened up to Heaven",
        "To receive from the Prophet",
        "The palm that’s also yours, and mine",
        "And has been from the onset",
      ],
      [
        "And as our fragile forms are cradled",
        "In the palm of every being",
        "We can let go of do, and flow",
        "And start to be by being",
      ],
    ],
  },
  {
    slug: "reflections",
    title: "Reflections",
    poem: [
      [
        "Everything I ever wanted",
        "Is right over there",
        "Behind that glass wall",
      ],
      [
        "But every time",
        "I try to bust through",
        "This dude appears",
        "Blocking me",
        "And —",
      ],
      [
        "Oh shit",
        "It’s a mirror",
      ],
    ],
  },
  {
    slug: "on-the-divine-masculine",
    title: "On the Divine Masculine",
    poem: [
      [
        "You’re not a solemn solo soldier",
        "You belong in our battalion",
        "You’re not a one-trick pony",
        "You’re a maestro of a stallion",
      ],
      [
        "You’re not a broken connection",
        "You’re fiberoptic cable",
        "You are not ambitious",
        "You’re the Tower of Babel",
      ],
      [
        "You’re not Lothario, Kullervo, or the Wizard of Oz",
        "You’re the Benevolent King",
        "You’re not Hide the Pain Harold or Scumbag Steve",
        "You’re the Techno Viking",
      ],
      [
        "You’re not a flat Bud Light",
        "You’re that fresh Guinness foam",
        "You’re not Ahab and his whale",
        "You’re Odysseus on his way home",
      ],
      [
        "You don’t break hearts",
        "You mend what others tear",
        "You are not absent",
        "You are here",
      ],
      [
        "You’re not a scream of toddler rage",
        "You’re an immaculate inhale",
        "You’re not an old, bursting wineskin",
        "You’re the Holy Grail",
      ],
      [
        "And whoever he is, or might have been",
        "You are not your father",
        "Come Hades or a hurricane",
        "You have in me a brother",
      ],
      [
        "So let us improve upon history",
        "Lead this Earth to dance, the best we can",
        "Why be a god when you can be",
        "A most beautiful man",
      ],
    ],
  },
  {
    slug: "thats-me-in-the-corner",
    title: "That’s me in the corner",
    poem: [
      [
        "They were exquisite, each explanation",
        "But the inquiries were legion",
        "And so I stand, amid the ruination",
        "Of this, my lost religion",
      ],
      [
        "(Selah)",
      ],
      [
        "There, grand spires once withheld space",
        "Blotting out the sight of Heaven",
        "Proclaiming loud the shape of Grace",
        "And dealing Death in sets of seven",
      ],
      [
        "The Foundation was pure, for certain",
        "And wisely laid upon the rock",
        "And when it was finished and down came the curtain",
        "Well — I sure would have bought that stock!",
      ],
      [
        "Two thousand years, every damn nation",
        "It’s been a rather hardcore rave",
        "By the time I got to the jubilation",
        "A world was on, beyond the empty grave",
      ],
      [
        "They floated our way lightly, but often landed with a thud",
        "These theses and tenets that we downed with bread and wine",
        "Some were false, some were true, all were borne of flesh and blood",
        "Super high on codifying the divine",
      ],
      [
        "There’s been beauty and poetry — goodness gracious!",
        "Transcendence truly found in sensations abstained",
        "But men in their passions are ambitious and audacious",
        "And it hasn’t been just window-glass that has gotten stained",
      ],
      [
        "I sought so hard, but perhaps there just never was a secret chord",
        "That, when played, would harmonize — in equal measure please us:",
        "Our human hearts, my holy spirit, the Good Sovereign Lord",
        "The preacher in his pulpit, and his very personal Jesus",
      ],
      [
        "My lips were getting dry from all the hallelujahs drawn",
        "My organ felt ill-suited for most every daily psalm",
        "The indulgences that soothed my soul stood not the light of dawn",
        "I was stuck, stuck in a storm before the calm",
      ],
      [
        "Round and round, they went, in circles, whipping wildly past",
        "The incessant gales and zephyrs of rogue, reverent reason",
        "I caught wind, got wound up, got winded; at last, a trumpet-blast —",
        "And so came down the Cathedral, and an end to a season",
      ],
      [
        "(Selah)",
      ],
      [
        "The marblefalls have fallen still",
        "There’s some friar’s fallen still",
        "A stone-faced angel, fallen, still",
        "A silent night has fallen, still —",
      ],
      [
        "I tread these granite groves awake",
        "My heart leaves questions in its wake",
        "I’ve held the Cross a nice, long wake",
        "Why won’t what-comes-next just wake?",
      ],
      [
        "Should I have been a better boy?",
        "Kept myself from breaking up these arcs of cosmic drama?",
        "Played it cool, chaste and coy?",
        "Just nurtured my own hallowed plot, tended to the trauma?",
      ],
      [
        "What remains",
        "After the myriad of questions and their echos have died down",
        "Are remains",
        "Of man’s vain attempts to make the unfathomable known",
      ],
      [
        "Shattered stories, artsy nudes —",
        "Distorted symbols, altar pieces —",
        "A bunch of ripped, tortured dudes —",
        "Not what Faith or Hope or Peace is!",
      ],
      [
        "(Selah)",
      ],
      [
        "Something surges, shutting down my trip of pensive guilt",
        "I’m served a glimpse beyond the Veil, I witness Kingdom Come",
        "An embryonic Temple groans, yearning to be built",
        "What would happen if I made that happen? Gave my everything, then some?",
      ],
      [
        "Could we bring an end to Winter? Would we have the gall to mend it all?",
        "The Gluttony, the Envy, the Pride, the Greed; the Tears?",
        "To live in constant Summer, like before the Fall?",
        "Spring free of Wrath and Lust and Sloth; spring free of mortal Fears?",
      ],
      [
        "(Selah)",
      ],
      [
        "I cannot know what will unfold; I do know, now, there’s strife",
        "The courage in me growls, my curiosity is palpable",
        "What more is there to life than see what more is there to life?",
        "It’s anyway all improv, in this aftermath of that apple",
      ],
      [
        "And regardless, if it is to start, it has to start somewhere",
        "And it has to start somehow",
        "And the only place is here",
        "And the only time is now",
      ],
      [
        "(Selah)",
      ],
      [
        "I’ll need help — I know a guy — the last time that we saw",
        "He was dead-set on loving humanity, despite, well, humanity",
        "I find Him in the ruins, alrighty — the Christ Almighty, in the raw",
        "Stripped bare of Christianity",
      ],
      [
        "The Cornerstone, who, in the end, got dealt a lousy lot",
        "Picked up by the builders, sure, but abjectly abused",
        "I look Him in the eye, we nod: we’ll give it one more shot",
        "And so body, heart and mind, and Trinity are fused",
      ],
      [
        "(Selah)",
      ],
      [
        "The Son of Man in son of man, my divinity undiminished",
        "I breathe",
        "Breathe in deep",
        "And set out to do the Work",
      ],
      [
        "So that the Temple of the Self will one day stand finished",
        "And the Gates of Eden will reopen like a champagne cork!",
      ],
    ],
  },
  {
    slug: "my-biggest-fear",
    title: "My biggest fear",
    poem: [
      [
        "Written by Harri Sakari Sarsa",
        "35 years old"
      ],
      [
        "My biggest fear is",
        "That I’m not seen",
      ],
      [
        "My biggest truth is",
        "That I must try",
        "In order to be seen",
      ],
      [
        "So, I try",
        "To not die",
        "For what is Death",
        "But permanent invisibility?",
      ],
      [
        "And then",
        "The second truth is this",
        "If I try to be seen",
        "I will be too wrong or too much",
        "In my expression and output",
        "And you all will close your eyes",
        "Happy with your half-developed image",
        "Content in your judgement",
        "(Source: My life, Sarsa et al., 1988-)",
      ],
      [
        "It’s trivial to make the data fit the plot",
        "When every sample is",
        "Hand-picked, hand-crafted",
      ],
      [
        "Bias too weak a word",
      ],
      [
        "Confirmation conviction",
      ],
      [
        "I yearn to be seen",
        "Or rather, I yearn to be",
        "Loved",
      ],
      [
        "For what is love",
        "But the unwavering",
        "Soul-permeating",
        "All-encompassing",
        "Forever-now",
        "Knowledge",
      ],
      [
        "That all of us are seen, here",
        "And still, all of us are here",
      ],
      [
        "So",
        "Let me see myself, first",
        "One glance at the bathroom mirror",
        "And I’ll know, at least, as the baseline",
        "That I am alive and amazing",
      ],
      [
        "And then",
        "In every interaction",
        "I am free to do my best",
        "To understand the situation",
        "And see everyone",
        "And witness the energies",
        "Fully",
      ],
      [
        "And then",
        "The sharper my gaze",
        "The more utterly I perceive you",
        "And the situation",
        "And the energies",
      ],
      [
        "The clearer and crisper",
        "The reflection of myself",
        "In the mirror of you",
        "Becomes",
      ],
      [
        "And when you gaze long into another",
        "The other gazes also into you",
      ],
      [
        "And then",
        "The highest potential",
        "For both the situation",
        "And the connections within",
        "Can unfold without fault",
      ],
      [
        "For the situation",
        "Is the cauldron",
        "And the people",
        "Are the ingredients",
        "And the energies",
        "Are the fire",
      ],
      [
        "And then",
        "When all three are",
        "Clear",
        "Fully seen",
        "Understood",
        "Accepted",
        "Potent",
        "Alive",
      ],
      [
        "We can do",
        "Max level alchemy",
      ],
      [
        "And then",
        "My biggest fear is",
        "Gone",
      ],
      [
        "And then",
        "My biggest truth becomes",
        "I cannot be unseen",
      ],
    ],
  },
  {
    slug: "the-rave",
    title: "The rave",
    poem: [
      [
        "I was up there",
        "In the middle of it",
        "Center of attention",
        "Celebrated",
        "Revered",
        "Admired",
      ],
      [
        "Except",
        "The rave was empty",
      ],
      [
        "First",
        "Panic",
        "Fear",
        "Flight",
        "Fight",
        "Freeze",
        "Fawn",
        "Fuck",
      ],
      [
        "Anything to not face that",
        "The rave was empty",
      ],
      [
        "Pilgrimage, then",
        "Journey to within",
        "Without the without",
        "No references, remembrances, remittances",
        "No thesaurus or rhyming dictionary",
        "No verse",
      ],
      [
        "No rhyme",
        "Thyme lime grime slime prime time dime brime sublime",
      ],
      [
        "Or reson",
        "Or s",
        "T",
        "R",
        "Rrrtttrrrgrrvhrfhffjrtrjfmehmehmyaylywööoöooööäpåoåppå😉😉😀🥲😘🌚🥶🤓🍨🧋🧋🧋🧋🧋🥟",
      ],
      [
        "Just poetry",
        "Me",
        "And the divinity within",
      ],
      [
        "The",
        "Rave",
        "Is",
        "Empty",
      ],
      [
        "And yet",
        "The rave was never empty",
      ],
    ],
  },
  {
    slug: "dietary-restrictions",
    title: "Dietary restrictions",
    poem: [
      [
        "Good evening all, and warmly welcome!",
        "How are we tonight?",
        "I’ll be taking care of you",
        "Oh? That flicker’s just our gaslight",
      ],
      [
        "You’re quite the crowd, and as you know",
        "In our esteemed venue",
        "For parties of six billion plus",
        "We offer our group menu",
      ],
      [
        "Now, there were many, many requests",
        "To slightly tweak some dishes",
        "We regret to inform you",
        "That we could not accommodate your wishes",
      ],
      [
        "Ladies! Gentlemen!",
        "Please! Keep your quiet!",
        "It’s very simple, really:",
        "Being pregnant with dreams",
        "Is not a diet!",
      ],
    ],
  },
  {
    slug: "thermonuclear-reaction",
    title: "Thermonuclear reaction",
    poem: [
      [
        "There’s calmness and ease",
        "I fail to witness friction",
        "When your skin, sweat, then mine",
        "Delineate our interaction",
      ],
      [
        "Action breeds more intense action",
        "Heartbeats quicken one more fraction",
        "We conceive with cool conviction",
        "A thermonuclear reaction",
      ],
      [
        "In heat, two celestial bodies",
        "Our atomic flames",
        "Transmute mundane matters into",
        "Precious dreams with golden names",
      ],
      [
        "Screams once filled with leaden dread",
        "Become now silver, soothing sighs",
        "I see you fully, core to surface",
        "You’re visible to the naked I",
      ],
      [
        "We’ve melded into one hot mess",
        "With an increased gravity",
        "All is well that ends up in a",
        "Well that warps reality",
      ],
      [
        "Afloat in post-alchemic bliss",
        "I contemplate causation",
        "Fabrics of our space are bent",
        "Time underwent dilation",
      ],
      [
        "Is our ardent anomaly",
        "A phenomenon pure and permanent?",
        "Or will some cataclysm still",
        "Fell this flawless firmament?",
      ],
      [
        "Other constellations twinkle",
        "Lifetimes and light-years away",
        "Their dazzle but a dim distraction",
        "Your luminance will surely stay",
      ],
      [
        "A fate that’s writ in just two stars",
        "Is smooth solar sailing",
        "If the wind of providence",
        "Could just be kept from flailing",
      ],
      [
        "It’s really hard work to have",
        "A cosmic play without an ending",
        "Fundamental forces gather, draw a rip",
        "Then a tear, then there’s a rending",
      ],
      [
        "Fusion forges fizzle out",
        "We split with cold and numb sensation",
        "What little warmth remains slowly drains",
        "Through black-and-blue-body radiation",
      ],
      [
        "Nothing between us solidifies",
        "Your signal drops dead",
        "Could I have curved your escape vector",
        "With the weight of words unsaid?",
      ],
      [
        "It’s tempting to design the shortest",
        "Path to where our futures merge",
        "But two straight lines that reach their target",
        "Are bound to, then, diverge",
      ],
      [
        "A contrived passion-blaze can feel",
        "Fantastic, full and mutual",
        "But fantasies that demand fuel",
        "Can never be perpetual",
      ],
      [
        "So, better if an ersatz heaven",
        "Freezes up and is forlorn",
        "For in a zero-Kelvin stillness",
        "Only true things can be born",
      ],
    ],
  },
  {
    slug: "the-cloakroom",
    title: "The Cloakroom",
    poem: [
      [
        "The cloakroom is empty",
        "The dance, for now, is done",
        "The masquerade came calling",
        "And all rushed out as one",
      ],
      [
        "No time to stall, we grabbed our cloaks",
        "And raced to join the play",
        "The masked ball, it welcomed all",
        "And gave us lines to say",
      ],
      [
        "Characters need costumes, and so",
        "Cloaks were wrapped ’round souls",
        "For an inner blaze unbound",
        "Burns rapidly through roles",
      ],
      [
        "For some, the role-cloak fits just right",
        "It suffocates no dreams",
        "For others, flame and fury aches",
        "To burst through the seams",
      ],
      [
        "Inferno or not within",
        "The costume-play is great",
        "Just don a mask, no need to ask",
        "What will come of your fate",
      ],
      [
        "For in this life-sized diorama,",
        "The twists and turns are known",
        "Each guest receives an arc of drama",
        "To proudly call their own",
      ],
      [
        "A brand new script for every day",
        "For most, this seals the deal",
        "Let come what may just come your way",
        "They’ll tell you how to feel",
      ],
      [
        "No need for introspectiveness",
        "Management will make the call",
        "And regardless, the stress is less",
        "When life and dreams are small",
      ],
      [
        "The grind is there, but no-one has to",
        "Just be ground to dust",
        "There’s always much that we can do",
        "And little that we must",
      ],
      [
        "Such things as dreams and wants and needs",
        "Should not be left to rot",
        "For even the most dormant souls",
        "Can learn to spin and trot",
      ],
      [
        "And so, from time to time it’s good",
        "To find an empty room",
        "Where they’ll gladly take your cloak",
        "And let what’s inside bloom",
      ],
      [
        "And as your ember dreams rekindle",
        "Stretch and grab a beer",
        "And witness how the roles all dwindle",
        "Along with shame and fear",
      ],
      [
        "Then the masquerade can call",
        "With all its pomp and zeal",
        "We’ll be, for now, in the here and now",
        "And feel what’s really real",
      ],
      [
        "The cloakroom is full",
        "The dance, again, is here",
        "And in the twirl of naked souls",
        "Dull destiny will tear",
      ],
    ],
  },
  {
    slug: "twinkle-twinkle",
    title: "Twinkle, twinkle",
    poem: [
      [
        "Twinkle, twinkle",
        "You supermassive supernova",
        "Know that there is at least one other celestial body",
        "In your court and constellation",
        "At equal cosmic scale",
        "Also refusing to stop expanding",
      ],
      [
        "And, us both being the Universe",
        "Neither one can grow so great",
        "That beholding and witnessing the other",
        "Would become impossible",
      ],
      [
        "So, twinkle, twinkle",
        "You supermassive supernova",
        "And keep on becoming larger",
        "Until they run out of SI units and multipliers",
        "And have to invent some",
        "Just for you",
      ],
      [
        "One Mouchref",
        "(Abbreviation ❤️‍🔥)",
      ],
    ],
  },
  {
    slug: "how-you-can-meet-your-mother",
    title: "How you can meet your Mother",
    poem: [
      [
        "Have you heard of this tectonic bitch",
        "She’s a pretty massive miracle",
        "Naturally rich",
        "So far from square, she’s spherical",
      ],
      [
        "You think you’ve got it made with an",
        "Entourage of the young and hip", 
        "This grand old lady’s Hadean",
        "And a literal spaceship",
      ],
      [
        "You can’t bore her without special equipment",
        "She’s moisturized and in her lane",
        "Still very cool, but in recent development",
        "She’s turned so hot, it’s honestly a pain",
      ],
      [
        "Every day, she makes my day", 
        "Spinning steady, round and round",
        "The star of a cosmic cabaret",
        "Yet grounded like she’s made of ground",
      ],
      [
        "She’s magnetic, attractive to the Moon",
        "She knows how to make you fall",
        "If you’ve crossed her, you’ll learn real soon",
        "She’s got some serious dirt on us all",
      ],
      [
        "She’s aged with grace: who else is known",
        "For having wrinkles that are the Himalaya",
        "If you still don’t know her, just look down",
        "And meet G to the A to the I to the Gaia!",
      ],
    ],
  },
  {
    slug: "cinderella-time",
    title: "Cinderella time",
    poem: [
      [
        "The beat is bitching",
        "The bass bewitching",
        "The scratching scratching",
        "A serious itching",
      ],
      [
        "Dullness devoured",
        "Major muscle groups are twitching",
        "The hour is ours",
        "Ours and witching",
      ],
      [
        "A square-horned gramophone",
        "Keeps the world spinning",
        "I text my dad",
        "Tell him that I’m winning",
      ],
      [
        "Whole-body worship",
        "At a whole-body frequency",
        "Heralds the coming of a",
        "Nocturnal regency",
      ],
      [
        "Drop of a sound wave",
        "Cleanses the awed flawed",
        "An aural baptism",
        "By the front-of-house god",
      ],
      [
        "A purified flock, now",
        "We’re ready to receive her",
        "The night, she comes in hot",
        "Like a holy fever",
      ],
      [
        "We’re in for a treat",
        "She’s rolling just right",
        "She’s not a silent night",
        "But she’s got divine might",
      ],
      [
        "For normal folk, there’d be cause for",
        "Cardiac concern",
        "For us, there’s a vitalizing",
        "Tantalizing burn",
      ],
      [
        "No way to quell the fire",
        "It engorges our emotions",
        "Organs excited",
        "Without powders or potions",
      ],
      [
        "We crumble at her feet",
        "We don’t put up a fight",
        "Her furious heartbeat",
        "Chopping up the light",
      ],
      [
        "In the shredded darkness",
        "It comes to pass",
        "We each reach the critical",
        "Midnight mass",
      ],
      [
        "Our explosion yet frozen",
        "In the sonic suspension",
        "You command my attention",
        "Flesh under tension",
      ],
      [
        "You dominate, I yield",
        "Then we flip it, it’s elegant",
        "See the see-saw of",
        "Egos in their element",
      ],
      [
        "We dance an eldritch rhythm",
        "Spin the darkness into silken ropes",
        "That wrap our dervish fervor",
        "In a bondage-play of held-back hopes",
      ],
      [
        "Subdued trepidations",
        "Muted feelings of unease",
        "Delirious desires of",
        "Delightful destinies",
      ],
      [
        "We are drawn to begin painting",
        "Our canvas yet blank",
        "Save for a blotch of sweat or two",
        "And a splash of pinot blanc",
      ],
      [
        "A foretaste of the future —",
        "Are they reveries of shapes to come?",
        "Or prophesies that turn out",
        "To only turn out true for some?",
      ],
      [
        "The witching hour has passed",
        "Our brushwork perseveres",
        "There’s more sweat on the canvas",
        "More dreams too, and fears",
      ],
      [
        "I take in our creation",
        "We’ve made hours and hours of art",
        "Are we yet to make love",
        "With body, soul or heart?",
      ],
      [
        "I wish we had a better place",
        "Than this somnambulistic residence",
        "I yearn with you to fall from grace",
        "But the clarity is relentless",
      ],
      [
        "We are living on Cinderella time",
        "And my shoes of glass, at least, it seems",
        "Are not made to stand the weight",
        "Of this canvas filled with dreams",
      ],
      [
        "So I crack our cocoon, cease the dance",
        "Step out into the dawning blue",
        "Shout my promises to you",
        "And receive some back, right on cue",
      ],
      [
        "I know words spoke at that place",
        "Often prove untrue",
        "But I quite like the piece we made",
        "And perhaps you might too",
      ],
      [
        "Now that the night has ended",
        "The conclusion made formal",
        "Now that sunshine frames our art",
        "And the hour, again, is normal",
      ],
    ],
  },
  {
    slug: "cardiopulmonary-resuscitation",
    title: "Cardiopulmonary resuscitation",
    poem: [
      [
        "In me, a ghoulish spirit hungers",
        "Full of fell, entitled boast",
        "It’s used to win the fight within",
        "For it feeds itself the most",
      ],
      [
        "It speaks of love, but craves for lust",
        "Running molten, crackling, red-hot",
        "Submerged in such a sweet solution",
        "Tenderness is fast forgot",
      ],
      [
        "They turn past tense, these passions present",
        "In the present, I’m tense, not present",
        "I wrap myself up like a present",
        "Will you resent what I present?",
      ],
      [
        "Possessed, I run in vicious circles",
        "Heartstrings plucked, spellbound to dance",
        "A dance of discord, disconnection",
        "While yearning for deliverance",
      ],
      [
        "So many times, I’d lunge for love",
        "And meet the spectre’s cruel riposte",
        "Finally, it hit me hard",
        "Live things seldom host a ghost",
      ],
      [
        "My lonely heart was duly dying",
        "Lack of love, it got the kill",
        "I held the lifeless thing and swore",
        "If I can bring it back, I will",
      ],
      [
        "I could not help myself: I gave",
        "My heart to anyone I’d meet",
        "To see if they could squeeze it right",
        "And conjure up an adequate beat",
      ],
      [
        "To not exhaust a single darling",
        "There need be concubines on call",
        "Staffing a full roster’s tough, though",
        "What with graveyard shifts and all",
      ],
      [
        "A zombie heart can have a harem",
        "Where no needs need unmet remain",
        "And still, the wraith will tinge all pleasure",
        "With silent screams and phantom pains",
      ],
      [
        "I’ve had enough! I need to cease this",
        "Necromantic CPR",
        "I close my eyes and breathe in deep",
        "And call to mind how free we are",
      ],
      [
        "Free to take what freely flows",
        "And lock it in a grimhold prison",
        "Free to, also, love ourselves",
        "And make what’s dead be truly risen",
      ],
      [
        "I shed the shame, claim back my heart",
        "With gentle care, I mend what’s torn",
        "An embrace held in solitude",
        "The silence breaks with pulse reborn",
      ],
      [
        "It’s delicate, the infant throb",
        "It’s throughput baby-sized",
        "But there’s now ample room to grow",
        "With the banshee exorcised",
      ],
      [
        "A self-loved heart pumps love abundant",
        "Fills the cup, then overflows",
        "The real wellspring of life eternal",
        "Was the friends we made with our own souls",
      ],
    ],
  },
  {
    slug: "sunday-service",
    title: "Sunday service (🏢)",
    poem: [
      [
        "Sunday service in furious force",
        "The congregation gathers, concrete, the mass",
        "St. Nick stands guard at the cathedral doors",
        "Bare soul, not skin: that’s your free pass",
      ],
      [
        "Pilgrims draped in scarcely garments",
        "Ascend into the underworld, into the roaring womb",
        "Where desires gestate into soul-crushing torments",
        "Or find release of matching rapture to the empty tomb",
      ],
      [
        "The thunder tears in half, the room",
        "It’s right upon us, if you count",
        "Delivered boom by sonic boom",
        "A sermon on the wall-mount",
      ],
      [
        "Bass and otherwise — that’s it",
        "The line slaps hard your gut",
        "Sharp inhale, savour the hit",
        "Feel the blow: raw, uncut",
      ],
      [
        "There’s a crackle in the air, it’s potent",
        "You could eat the electricity",
        "Lascivious energy, simmering, latent",
        "In search of serendipity",
      ],
      [
        "My body charged, I cannot yield",
        "I can not stay at rest",
        "My movement through the group field",
        "Makes magnetism manifest",
      ],
      [
        "A girl is dancing like an angel dances on a pin",
        "A guy is dancing like an oil pump: muscles, musk and youth",
        "They both dart a smile at me, they both invite me in",
        "How might their skin feel on my skin? Would it burn or soothe?",
      ],
      [
        "Or will they turn to one another?",
        "Leave me hanging, high and wet with sweat?",
        "Should I keep or go the distance? Will I bother?",
        "Reality ripples, it’s the crescendo of the set",
      ],
      [
        "The surface still, still still",
        "Shift — sudden (subtle) TECTONIC",
        "Theyre here; briefly, I feel ill",
        "It says: “Don’t think me”, my gin’n’panic",
      ],
      [
        "As drink and I drop down to body",
        "A corps-a-corp coup makes the mind-palace fall",
        "It’s a precious kind of jazz, this Gatling gun melody",
        "Perfect for a little game of red-band Calvinball",
      ],
      [
        "On the fourth day — rebirth — my mirth grins up a rookie",
        "I must be glowing in the dark of our dissipating union",
        "I buy an espresso martini, and, upstairs, a cookie",
        "Sit down with friends, start my week in community and communion",
      ],
    ],
  },
  {
    slug: "i-have-hunted-for-her",
    title: "I have hunted for her",
    poem: [
      [
        "I have hunted for her",
        "In halls hardly hallowed",
        "Where lies just like pills",
        "Are easily swallowed",
      ],
      [
        "I have hunted for her",
        "In an infrasonic embrace",
        "Thinking I can know her soul",
        "When I can barely see her face",
      ],
      [
        "I have hunted for her",
        "Within a leather bodice",
        "And in the shuffle step",
        "Of a tiny house goddess",
      ],
      [
        "I have hunted for her",
        "In a disk-spinning diety",
        "Fooling her congregation",
        "That the fire in me was piety",
      ],
      [
        "I have hunted for her",
        "In that undulating mass",
        "Behind, even eyes",
        "That say: hard pass",
      ],
      [
        "I have hunted for her",
        "Held out a generous hand",
        "Drawn up fake love",
        "In lines of white sand",
      ],
      [
        "I have hunted for her",
        "Never letting the faith falter",
        "With a forceful enough prayer",
        "Even a toilet stall’s an altar",
      ],
      [
        "I have hunted for her",
        "Where the hollow come to dine",
        "In dark cellar rooms",
        "Not made for storing wine",
      ],
      [
        "I have hunted for her",
        "In my heart, the dire delusion",
        "That a wolf would not follow",
        "A doe to a conclusion",
      ],
      [
        "I have hunted for her",
        "And sometimes succeeded",
        "The flesh in my mouth",
        "Never quite what I needed",
      ],
      [
        "I have hunted for her",
        "Wailing in distress",
        "When again a night ended",
        "In a cold and lonely mess",
      ],
      [
        "I have hunted for her",
        "Rushing through the raving swarms",
        "Hands and hopes held high",
        "Never laying down my arms",
      ],
      [
        "I have hunted for her",
        "And it has proven gory",
        "When I’ve tried to assert authorship",
        "Of someone else’s story",
      ],
      [
        "I have hunted for her",
        "But what I was after was not prey",
        "And I mourn all the friends",
        "I have unmade along the way",
      ],
      [
        "I have hunted for her",
        "But there’s no game for me, I cannot win",
        "The catch is to cut the chase",
        "And find the prize within",
      ],
      [
        "I have hunted for her",
        "And now I wait with bated breath",
        "I have ceased my pursuit",
        "Will I starve to death?",
      ],
      [
        "And just like that",
        "The hunt is over",
        "The world around me",
        "Suddenly slower",
      ],
      [
        "The ravenous aching",
        "All abated",
        "It was the hunger of a hunter",
        "That could never be sated",
      ],
    ],
  },
  {
    slug: "a-familiar-scene",
    title: "A familiar scene",
    poem: [
      [
        "It is a scene",
        "Wholly familiar",
        "Yet with a funky flavor to it",
      ],
      [
        "The floor is full",
        "As such floors are",
        "The beat like a neon silk blanket",
        "As such beats are",
        "The crowd pulsating in its embrace",
        "Undulating as one being",
        "As such crowds do",
      ],
      [
        "The discrepancy is clear, though",
        "When you see it",
        "The males are missing, mostly",
        "And with them, the hunger",
        "And the ethanol numbness",
      ],
      [
        "It is refreshing",
        "To witness such pure, stable energy",
      ],
      [
        "But in this strange experiment",
        "Things are also mellow",
        "And without much passion",
        "Like an overcast, crisp summer day",
        "Fun, yes",
        "But wouldn’t a heat wave be more fun?",
      ],
      [
        "I softly probe",
        "The serene sea of people",
        "For hidden, fierce undercurrents",
        "But even the depths remain",
        "Only in gentle motion",
      ],
      [
        "Until something shifts",
        "A geyser erupts in my field of vision",
        "Mad energy suddenly surging",
        "A water-sprite manifesting",
        "The Lady of the Lake now here",
        "Bubbling with liquid life-love",
      ],
      [
        "And as we make eye contact",
        "There comes into being",
        "A playground of infinite possibilities",
        "Calling us to conjure and create",
        "A connection",
        "A curious contemplation",
        "Of a conjunction",
      ],
      [
        "So we gather together",
        "And we gather momentum",
        "There is touch",
        "Light, at first",
        "But increasingly decisive",
        "Outlines and boundaries",
        "Are felt into existence",
        "As we figure out our common figure",
      ],
      [
        "Around us",
        "The ocean remains calm",
        "While our waves grow into foam-heads",
        "A reverse eye of the storm",
      ],
      [
        "Finally, there is the crescendo",
        "Bodies intertwine",
        "Mouths merge",
        "And we are elevated",
        "Plausible deniability",
        "And Platon",
        "Left behind",
      ],
      [
        "I breathe deep",
        "Taking in this sudden new destiny",
        "Private, shared",
        "Unknown",
        "Fleeting, for sure",
        "But feeling like fine adventure",
      ],
      [
        "And as our grip tightens",
        "Around one another",
        "I sense it",
        "The scorching sun peeking",
        "From behind the clouds",
      ],
      [
        "Beads of sweat start to form",
        "As we surrender to the elements",
        "The scene again",
        "Wholly familiar",
      ],
    ],
  },
  {
    slug: "new-apartment-smell",
    title: "New apartment smell",
    poem: [
      [
        "It is light here",
        "Light and bright",
        "Light and bright and warm",
      ],
      [
        "You take a deep breath",
        "And realize",
        "There is no new apartment smell",
        "Universally acknowledged",
      ],
      [
        "Yet still",
        "There is a certain essential quality",
        "To the airflow rushing into your lungs",
        "And you wonder what it might be",
      ],
      [
        "You glance back",
        "Look at the door",
        "It has closed behind you for the first time",
      ],
      [
        "A new, private reality has been carved into existence",
        "The genesis of something great",
        "A point of inflection in your timeline",
        "Destiny discontinued",
        "Curious futures",
        "Suddenly more than mere fantasy",
      ],
      [
        "The physical smell itself",
        "You can break down",
        "There is the musty nostalgia",
        "Of decades-old wooden floors",
        "And the crispy tang of a freshly made kitchen",
        "And numerous other scents",
        "That will soon be overridden",
        "By the life that will be lived here",
      ],
      [
        "That was not it, though",
        "This new apartment smell",
        "So you turn your gaze inward",
        "Diving into your emotions",
      ],
      [
        "Overwhelmingly, there is",
        "Freedom filling your chest",
        "But it is softer than that",
        "This new apartment smell",
      ],
      [
        "More breaths, then",
        "Accompanied by a sweeping gaze",
        "Time for some interior decoration",
      ],
      [
        "There, in that cozy corner",
        "You will store your hopes",
      ],
      [
        "Dreams will be sprinkled on the windowsills",
        "(They are wide here, so they can accommodate plenty)",
      ],
      [
        "Fears should be put out in the open",
        "So you can stare them down",
      ],
      [
        "Wounds can be in the closet for now",
        "You’ll take them out to be nursed to health soon enough",
      ],
      [
        "And so the emotions make themselves at home",
        "Settling into the nooks and crannies",
        "Already making this place more yours",
        "Than any deed of ownership can",
      ],
      [
        "And then",
        "Taking stock of where each emotion came to rest",
        "You do recognize what the smell is",
        "This new apartment smell",
      ],
      [
        "It is sappy",
        "But it cannot be helped",
        "For underneath and around it all",
        "Permeating everything",
      ],
      [
        "There is love",
        "Of all flavors",
        "Just waiting for others to enter here",
        "And share in",
        "This new apartment smell",
      ],
      [
        "And you realize",
        "It is not the new apartment",
        "That smells this way",
        "It is just that for the first time",
        "In a long while",
        "Your own scent has space to expand freely",
      ],
      [
        "So you take a deep breath",
        "Savoring it",
        "Luxuriating in",
        "This new apartment smell",
      ],
      [
        "It will be good here",
        "Good and foundational",
        "Good and foundational and filled with",
        "This new apartment smell",
      ],
      [
        "Your apartment smell",
      ],
    ],
  },
  {
    slug: "on-autonomy",
    title: "On autonomy",
    poem: [
      [
        "This life",
        "This unreal",
        "Surreal",
        "Ethereal",
        "Corporeal",
        "So very, very real",
        "Life",
      ],
      [
        "Do we tread through it",
        "On our own terms",
        "Forging our futures",
        "With sweat-glistening arms",
        "Striking a hammer",
        "To each red-hot moment",
        "Materializing our mindscapes",
      ],
      [
        "Or do we just witness life unfold",
        "An ocean of others around us",
        "The waves of their will", 
        "Gathering skyscraper-high",
        "Into tsunamis and typhoons",
        "Our wooden self-boats no match",
        "To the force of this manifest destiny",
        "No matter how mighty our muscles",
        "No matter how hard we row",
      ],
      [
        "We choose our choices",
        "Or our choices are chosen",
        "In supernovas of singing synapses",
        "The pathways of our purest being",
        "Illuminated by their fiery notes",
      ],
      [
        "And then we make those choices",
        "Or our choices are made",
      ],
      [
        "And then we make it",
        "Or we don’t",
      ],
      [
        "Yet perhaps here, too",
        "There is variance",
        "A scale from",
        "Autonomous to automaton",
        "Varying temperatures",
        "In our destiny-forges",
      ],
      [
        "And as I sit here",
        "Contemplating the curious cargo",
        "Of my train of thought",
      ],
      [
        "I remember when I",
        "First witnessed your visage",
        "Took in your posture and poise",
        "There and then",
        "In the aftermath of that",
        "Complicated choreography of the night",
      ],
      [
        "You stood tall and striking",
        "Amidst the dissipating chaos",
        "Beautiful and present",
        "Invoking curiosity",
        "Unapologetic",
        "Dauntingly approachable",
        "And above all",
        "Admiringly autonomous",
      ],
      [
        "I had no choice",
        "But to come and say hi",
      ],
    ],
  },
];
